### ISSUE TITLE
normalize.quantiles doesn't exist

### ISSUE THREAD

**Issue by deisygysi** [lihuamei/LinDeconSeq#1]
Could you please help me?

I believe a pointer is missing in the code. The function probably comes from another package, when checking the code for normalizeData, the function is called (probably from another package) without proper reference (package::normalize.quantiles). 

Best, 
d

> library(LinDeconSeq)
> pures <- shen_orr$data[, rowSums(shen_orr$annotation$pure) != 0 ]
> markerRes <- findMarkers(pures, shen_orr$phenotypes, min.group = 100, max.group = 300, norm.method = 'QN', data.type = 'MA')
[INFO] There are 6669 samples and 42 genes in the reference profile
Error in normalize.quantiles(X) : 
  could not find function "normalize.quantiles"

**Comment by lihuamei** [comment]
Dear Gysi, 
       I have updated the code and fix the bugs in it, thaks so much!
Best
